// Number Eight: Write addition, subtraction, multiplication, and division operations that each result in the number 8. Be sure to enclose your operations in print statements to see the results.
console.log("ADDITION");
var first = 4 + 4;
console.log(first);
var second = 1 + 7;
console.log(second);
console.log("SUBTRACTION");
var third = 12 - 4;
console.log(third);
var fourth = 16 - 8;
console.log(fourth);
console.log("MULTIPLICATION");
var fifth = 4 * 2;
console.log(fifth);
var sixth = 8 * 1;
console.log(sixth);
console.log("DIVISION");
var seventh = 16 / 2;
console.log(seventh);
var eighth = 32 / 4;
console.log(eighth);
